### ISSUE TITLE
MotoButtons 2

### ISSUE THREAD

**Issue by MotoMongrel** [joncox123/MotoButtons2#1]
Hi Mate,
So happy you're making version 2. I have a Ruffy 4 way and 5 way joystick and was about to solder up your original design, but now I'll wait till you've finished version 2. Would it be possible to create 2 versions of the firmware, one with the 4 way joystick and one for the 5 way, giving an extra junction without taking up any more room in the case? Here is a pic of the two setups I made for MotoButtons 1.
![430433651_1684552032349184_4186370763419778033_n](https://github.com/joncox123/MotoButtons2/assets/163205263/9c8c2fba-7892-4e5e-9392-c1cd70aece1c)
![430400609_1362535241116066_6952532755814372741_n](https://github.com/joncox123/MotoButtons2/assets/163205263/dd7e2242-9958-45a9-8140-52f73bab2ff9)

It mounts to the left hand rear brake lever.

**Comment by joncox123** [comment]
Nice work, I really like your design. Mine is a little more boxy. I will be completing MotoButtons 2 construction and coding this week. In turns out, I got a good deal on a 4-way joystick that is normally $300. So I'll actually be writing the code for a 4-way at first.
