### ISSUE TITLE
Code Update?

### ISSUE THREAD

**Issue by MotoMongrel** [joncox123/MotoButtons2#2]
![440745372_438343168934352_8297625169892155326_n](https://github.com/joncox123/MotoButtons2/assets/163205263/1608e6a9-15aa-4d7d-af04-9b7f6692e7f7)
![441437835_950430960145467_2557775888606659077_n](https://github.com/joncox123/MotoButtons2/assets/163205263/6481d526-017a-4c21-b465-cba8badc050a)
Hi,
Any update on the Code. I've designed 2 options for the cases .

**Comment by joncox123** [comment]
Wow, the good work keeps coming. I will be completing the MotoButtons 2 code this week.

**Comment by MotoMongrel** [comment]
I ended up going with Razorpad code here on GitHub as it's been a few months with no reply from you. I thought that maybe you'd decided not to continue with it. All good

**Comment by gasperzupancic** [comment]
@MotoMongrel can you share the 3d print files maybe?

**Comment by MotoMongrel** [comment]
> @MotoMongrel can you share the 3d print files maybe?

It's custom designed to bolt to my left hand rear brake, not the handlebars. Here's a link to what I've done that properly explains better what I've done.   https://www.facebook.com/share/fencRY91Z7r1L4gP/

**Comment by MotoMongrel** [comment]
> @MotoMongrel can you share the 3d print files maybe?


I ended up going with the Razorpad firmware on Github. Here is the finished remote
![461559956](https://github.com/user-attachments/assets/ca9ff866-9374-43d7-a358-513755929e77)

**Comment by joncox123** [comment]
3D files are already posted on the repo. Check the instructions.
