### ISSUE TITLE
3d printing service - I can do it. 

### ISSUE THREAD

**Issue by downerhouse** [joncox123/MotoButtons2#4]
When you are ready with your final design, id be happy to discuss a very low cost 3d printing service I can provide for the case. I'd need the CAD files to be able to give an estimate. Pretty sure I'll be a lot cheaper than anyone else - postage is likely to be the highest element of the cost.

**Comment by joncox123** [comment]
I had this printed in Nylon SLA via Cloudcraft for only $15. I am not in the business of selling these, it's only an open-source design.
